### ISSUE TITLE
Error: The request you have made requires authentication

### ISSUE THREAD

**Issue by soichih** [godaddy/node-openstack-wrapper#15]
Hello. I have following test code

```
const openstack = require('openstack-wrapper');
const keystone = new openstack.Keystone(process.env.OS_AUTH_URL);
keystone.getToken(process.env.OS_USERNAME, process.env.OS_PASSWORD, function(err, token) {
    console.dir(err);
    console.dir(token);
});
```

which is outputting this.

```
{ [Error: The request you have made requires authentication.]
  status: 401,
  detail: 'Remote Method: POST\nRemote Uri: https://my.openstack.url:35357/v3/auth/tokens\nRemote Details: ',
  code: undefined }
```

Does openstack-wrapper support v3.6 API?

**Comment by BannedInSweden** [comment]
V3 yes - v3.6...i'm not certain though I don't think keystone was into the minor versioning like nova has started doing yet so I assume yes.

**Comment by BannedInSweden** [comment]
Juuuuust realizing this comment was a few years old.  Going to go ahead and close this one.  If the issue still remains please feel free to open a new comment and a response should be prompt.
