### ISSUE TITLE
Support for Designate?

### ISSUE THREAD

**Issue by lklepner** [godaddy/node-openstack-wrapper#4]
Hi,

Reading over the capabilities I don't see any mention of designate. Is there any plan to provide support for it?

Thanks,
Lou

**Comment by BannedInSweden** [comment]
Hi Lou,

      First up - I'm sorry for the delayed reply.  My Github account was 
hooked up to an email hole.  Fixed that today and saw your message.

As for Designate - The shop I'm in uses a custom DNS endpoint/service 
for record modification (as opposed to designate) so its not in the lib. 
  I should be able to tack on the basic CRUD commands though for 
designate if you like?  Alternatively let me know if you'd like to 
tackle it and I can review/merge in the changes.

Thanks for reaching out to me,

Jason R.

.On 2016-01-20 08:46, Lou Klepner wrote:

**Comment by BannedInSweden** [comment]
No reply in the last year - closing issue until there are further requests for designate.
